name: super_simple_authentication_server
description: The server for Super Simple Authentication.
version: 0.0.1-dev.1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  dart_frog: 1.2.6
  mason_logger: ^0.3.3
  super_simple_authentication_hive_data_storage: 0.0.1-dev.2
  super_simple_authentication_postgres_data_storage: 0.0.1-dev.4
  super_simple_authentication_toolkit: 0.0.1-dev.9

dev_dependencies:
  json_serializable: ^6.11.3
  mocktail: ^1.0.3
  test: ^1.28.0
  very_good_analysis: ^10.0.0
