name: super_simple_authentication_hive_data_storage
description: A DataStorage that stores information to a Hive storage
version: 0.0.1-dev.1
repository: https://github.com/mtwichel/super_simple_flutter_authentication/tree/main/packages/super_simple_authentication_hive_data_storage

environment:
  sdk: ^3.8.0

dependencies:
  hive_ce: ^2.11.3
  super_simple_authentication_toolkit: ^0.0.1-dev.1
  uuid: ^4.5.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ">=9.0.0 <11.0.0"
