name: super_simple_authentication_toolkit
description: A collection of Dart Frog functions that power the super_simple_authentication_server
version: 0.0.1-dev.4
repository: https://github.com/mtwichel/super_simple_flutter_authentication/tree/main/packages/super_simple_authentication_toolkit

environment:
  sdk: ^3.8.0

dependencies:
  dart_frog: ^1.2.3
  http: ^1.5.0
  meta: ^1.17.0
  pointycastle: ^4.0.0
  uuid: ^4.5.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
